# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec7f753830fccc126569de50801b446588f3a45703933326083e8e5498bb75d0b5067cb7a4443b851320769f8a947d6d3d5f738f634c578aea35fc1ec6372dd0

test:
  secret_key_base: d3fdc5becc36dc7f6dbad1ca51fc1f449a15cd717a0e09f870fdfc164c26d4e73886e0d263392a71a191154d9848a7e26cad31a9d7138323b6f938c1dbf82a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
